
var listparamecia = ["Gomu Gomu no Mi","Bara Bara no Mi","Sube Sube no Mi","Bomu Bomu no Mi","Kiro Kiro no Mi","Hana Hana no Mi","Doru Doru no Mi","Baku Baku no Mi","Mane Mane no Mi","Supa Supa no Mi","Toge Toge no Mi","Ori Ori no Mi","Bane Bane no Mi","Ito Ito no Mi","Noro Noro no Mi","Doa Doa no Mi","Awa Awa no Mi","Beri Beri no Mi","Sabi Sabi no Mi","Shari Shari no Mi","Horo Horo no Mi","Yomi Yomi no Mi","Kage Kage no Mi","Suke Suke no Mi","Nikyu Nikyu no Mi","Jiki Jiki no Mi","Ope Ope no Mi","Shiro Shiro no Mi","Wara Wara no Mi","Oto Oto no Mi","Mero Mero no Mi","Doku Doku no Mi","Horu Horu no Mi","Choki Choki no Mi","Gura Gura no Mi","Kira Kira no Mi","Poke Poke no Mi","Woshu Woshu no Mi","Fuwa Fuwa no Mi","Gura Gura no Mi","Mato Mato no Mi","Fuku Fuku no Mi","Hobi Hobi no Mi","Buki Buki no Mi","Guru Guru no Mi","Beta Beta no Mi","Zushi Zushi no Mi","Bari Bari no Mi","Nui Nui no Mi","Giro Giro no Mi","Ato Ato no Mi","Jake Jake no Mi","Pamu Pamu no Mi","Sui Sui no Mi","Ton Ton no Mi","Hira Hira no Mi","Ishi Ishi no Mi","Fude Fude no Mi","Nagi Nagi no Mi","Chiyu Chiyu no Mi","Soru Soru no Mi","Mira Mira no Mi","Pero Pero no Mi","Bisu Bisu no Mi","Bata Bata no Mi","Buku Buku no Mi","Kuri Kuri no Mi","Shibo Shibo no Mi","Memo Memo no Mi","Mochi Mochi no Mi ","Hoya Hoya no Mi","Netsu Netsu no Mi","Soru Soru no Mi","Kuku Kuku no Mi","Gocha Gocha no Mi","Oshi Oshi no Mi","Kobu Kobu no Mi","Kibi Kibi no Mi","Toki Toki no Mi","Juku Juku no Mi","Suke Suke no Mi","Mane Mane no Mi","Bari Bari no Mi","Maki Maki no Mi","Goe Goe no Mi","Hiso Hiso no Mi","Kama Kama no Mi","Kachi Kachi no Mi","Nemu Nemu no Mi","Mini Mini no Mi","Atsu Atsu no Mi","Noko Noko no Mi","Ami Ami no Mi","Mosa Mosa no Mi","Modo Modo no Mi","Gutsu Gutsu no Mi","Peto Peto no Mi","Moa Moa no Mi","Kyubu Kyubu no Mi","Nuke Nuke no Mi","Koro Koro no Mi","Jara Jara no Mi","Iro Iro no Mi","Goru Goru no Mi","Raki Raki no Mi","Bijo Bijo no Mi","Gasha Gasha no Mi"];
var listzoan = ["Ushi Ushi no Mi, Model: Bison","Hito Hito no Mi","Tori Tori no Mi, Model: Falcon","Inu Inu no Mi, Model: Dachshund","Mogu Mogu no Mi","Inu Inu no Mi, Model: Jackal","Uma Uma no Mi","Neko Neko no Mi, Model: Leopard","Zou Zou no Mi","Inu Inu no Mi, Model: Wolf","Ushi Ushi no Mi, Model: Giraffe","Hebi Hebi no Mi, Model: King Cobra","Hebi Hebi no Mi, Model: Anaconda","Tori Tori no Mi, Model: Phoenix ","Hito Hito no Mi, Model: Daibutsu ","Kame Kame no Mi","Artificial Uo Uo no Mi, Model: Seiryu ","Sara Sara no Mi, Model: Axolotl","Mushi Mushi no Mi, Model: Kabutomushi","Mushi Mushi no Mi, Model: Suzumebachi","Zou Zou no Mi, Model: Mammoth ","Tama Tama no Mi","Tori Tori no Mi, Model: Albatross","Inu Inu no Mi, Model: Tanuki","Ryu Ryu no Mi, Model: Allosaurus ","Ryu Ryu no Mi, Model: Spinosaurus ","Ryu Ryu no Mi, Model: Pteranodon ","Ryu Ryu no Mi, Model: Brachiosaurus ","Ryu Ryu no Mi, Model: Pachycephalosaurus ","Ryu Ryu no Mi, Model: Triceratops ","Kumo Kumo no Mi, Model: Rosamygale Grauvogeli ","Neko Neko no Mi, Model: Saber Tiger ","Uo Uo no Mi, Model: Seiryu ","Inu Inu no Mi, Model: Kyubi no Kitsune ","Hebi Hebi no Mi, Model: Yamata no Orochi ","Hito Hito no Mi, Model: Onyudo ","Inu Inu no Mi, Model: Okuchi no Makami ","Hito Hito no Mi, Model: Nika ","Tori Tori no Mi, Model: Eagle","Sheep SMILE","Mouse SMILE","Bat SMILE","Gazelle SMILE","Lion SMILE","Horse SMILE","Hippopotamus SMILE","Alpaca SMILE","Scorpion SMILE","Elephant SMILE","Monkey SMILE","Armadillo SMILE","Ostrich SMILE","Flying Squirrel SMILE","Gorilla SMILE","Giraffe SMILE","Chicken SMILE","Rattlesnake SMILE","Bear SMILE","Pug SMILE","Hognose Snake SMILE","White Snake SMILE","Snake SMILE","Rabbit SMILE","Caiman SMILE","Tiger SMILE","Llama SMILE"];
var listlogia = ["Moku Moku no Mi","Suna Suna no Mi","Mera Mera no Mi","Goro Goro no Mi","Hie Hie no Mi","Yami Yami no Mi","Pika Pika no Mi","Magu Magu no Mi","Numa Numa no Mi","Gasu Gasu no Mi","Yuki Yuki no Mi","Mera Mera no Mi","Toro Toro no Mi","Ame Ame no Mi"];
var listfruits = [].concat(listparamecia, listzoan, listlogia);
var listtype = ["Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia"];
var listsubtype = ["Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Special","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Paramecia","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Zoan","Ancient","Ancient","Ancient","Ancient","Ancient","Ancient","Ancient","Mythical","Mythical","Mythical","Mythical","Mythical","Mythical","Zoan","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","SMILE","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia","Logia"];
var listcanon = [true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,true,false,false];
var listusers = ["Monkey D. Luffy (Paramecia)","Buggy","Alvida","Gem","Mikita","Nico Robin","Galdino","Wapol","Bentham","Daz Bonez","Zala","Hina","Bellamy","Donquixote Doflamingo","Foxy","Blueno","Kalifa","Very Good","Shu","Sharinguru","Perona","Brook","Gecko Moria","Absalom","Bartholomew Kuma","Eustass Kid","Trafalgar D. Water Law","Capone Bege","Basil Hawkins","Scratchmen Apoo","Boa Hancock","Magellan","Emporio Ivankov","Inazuma","Edward Newgate","Jozu","Blamenco","Tsuru","Shiki","Marshall D. Teach (Paramecia)","Vander Decken IX","Kin'emon","Sugar","Baby 5","Buffalo","Trebol","Issho","Bartolomeo","Leo","Viola","Giolla","Kelly Funk","Gladius","Senor Pink","Machvise","Diamante","Pica","Kurozumi Kanjuro","Donquixote Rosinante","Mansherry","Charlotte Linlin","Charlotte Brûlée","Charlotte Perospero","Charlotte Cracker","Charlotte Galette","Charlotte Mont-d'Or","Charlotte Opera","Charlotte Smoothie","Charlotte Pudding","Charlotte Katakuri","Charlotte Daifuku","Charlotte Oven","Carmel","Streusen","Charlotte Newshi","Belo Betty","Morley","Tama","Kozuki Toki","Shinobu","Shiryu","Kurozumi Higurashi","Kurozumi Semimaru","Raizo","Eldoraggo","Apis","Eric","Bear King","Noko","Lily Enstomach","Accino","Musshuru","Largo","Binz","Ain","Bill","Breed","Byrnndi World","Gairam","Tanaka","Aveyron","Mad Treasure","Psycho P","Gild Tesoro","Baccarat","Ann","Douglas Bullet","Dalton","Tony Tony Chopper","Pell","Lassoo","Drophy","Chaka","Pierre","Rob Lucci","Funkfreed","Jabra","Kaku","Boa Marigold","Boa Sandersonia","Marco","Sengoku","Pekoms","Kozuki Momonosuke","Smiley","Kabu","Bian","Jack","Tamago","Morgans","Bunbuku","X Drake","Page One","King","Queen","Ulti","Sasaki","Black Maria","Who's-Who","Kaidou","Catarina Devon","Kurozumi Orochi","Onimaru","Yamato","Monkey D. Luffy (Zoan)","Buzz","Sheepshead","Mouseman","Batman","Gazelleman","Holdem","Speed","Dobon","Alpacaman","Daifugo","Babnuki","Solitaire","Madilloman","Dachoman","Bao Huang","Briscola / Mizerka","Hamlet","Fourtricks","Poker","Bearman","Wanyudo","Nure-Onna","Tenjo-Sagari","Snakeman / Sarahebi","Rabbitman","Caimanlady","Tigerman","Llamaman","Smoker","Crocodile","Portgas D. Ace","Enel","Kuzan","Marshall D. Teach (Logia)","Borsalino","Sakazuki","Caribou","Caesar Clown","Monet","Sabo","Honey Queen","Gasparde"];
var listappearance = ["East Blue","East Blue","East Blue","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Sky Island","Sky Island","Water Seven","Water Seven","Water Seven","Water Seven","Water Seven","Water Seven","Thriller Bark","Thriller Bark","Thriller Bark","Thriller Bark","Thriller Bark","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Summit War","Movie","Sky Island","Fishman Island","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Summit War","Four Emperors","Four Emperors","Four Emperors","Movie","Filler","Filler","Movie","Filler","Filler","Filler","Movie","Filler","Movie","Movie","Filler","Filler","Filler","Filler","Movie","Filler","Filler","Filler","Movie","Movie","Movie","Movie","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Arabasta","Sky Island","Water Seven","Water Seven","Water Seven","Water Seven","Summit War","Summit War","Summit War","Summit War","Fishman Island","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Four Emperors","Fishman Island","Four Emperors","Four Emperors","Summit War","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Dressrosa","Summit War","Four Emperors","Four Emperors","Four Emperors","East Blue","Movie","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","Four Emperors","East Blue","Arabasta","Arabasta","Sky Island","Water Seven","Sky Island","Summit War","Water Seven","Fishman Island","Dressrosa","Dressrosa","Summit War","Movie","Movie"];
var listsubappearance = ["Romance Dawn","Orange Town","Romance Dawn","Whisky Peak","Whisky Peak","Whisky Peak","Little Garden","Drum Island","Little Garden","Arabasta","Arabasta","Arabasta","Jaya","Dressrosa","Long Ring Long Land","Water Seven","Water Seven","Enies Lobby","Enies Lobby","Enies Lobby","Thriller Bark","Thriller Bark","Thriller Bark","Thriller Bark","Thriller Bark","Sabaody Archipelago","Sabaody Archipelago","Sabaody Archipelago","Sabaody Archipelago","Sabaody Archipelago","Amazon Lily","Impel Down","Impel Down","Impel Down","Marineford","Marineford","Marineford","Marineford","Strong World","Jaya","Fishman Island","Punk Hazard","Punk Hazard","Punk Hazard","Punk Hazard","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Dressrosa","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Whole Cake Island","Flashback","Whole Cake Island","Whole Cake Island","Levely","Levely","Wano","Wano","Wano","Impel Down","Flashback","Flashback","Zou","The Movie","Warship Island","Warship Island","Clockwork Island Adventure","Ocean's Dream","Film Z","Ice Hunter","Episode of Chopper","Strong World","Film Z","Film Z","Film Gold","Caesar Retrieval","3D2Y","3D2Y","Film Gold","Film Gold","Film Gold","Film Gold","Film Gold","Film Gold","Stampede","Stampede","Drum Island","Drum Island","Arabasta","Arabasta","Arabasta","Arabasta","Skypiea","Water Seven","Enies Lobby","Enies Lobby","Water Seven","Amazon Lily","Amazon Lily","Marineford","Marineford","Fishman Island","Punk Hazard","Punk Hazard","Dressrosa","Dressrosa","Zou","Fishman Island","Whole Cake Island","Wano","Sabaody Archipelago","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Dressrosa","Impel Down","Wano","Wano","Wano","Romance Dawn","3D","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Wano","Loguetown","Arabasta","Arabasta","Skypiea","Long Ring Long Land","Jaya","Sabaody Archipelago","Marineford","Sabaody Archipelago","Punk Hazard","Punk Hazard","Dressrosa","Clockwork Island Adventure","Dead End Adventure"];
var listaffiliation = ["Pirate","Pirate","Pirate","Civilian","Civilian","Pirate","Pirate","Civilian","Civilian","Pirate","Civilian","Government","Pirate","Pirate","Pirate","Government","Government","Government","Government","Government","Pirate","Pirate","Pirate","Pirate","Civilian","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Government","Civilian","Civilian","Pirate","Pirate","Pirate","Government","Pirate","Pirate","Pirate","Civilian","Pirate","Pirate","Pirate","Pirate","Government","Pirate","Pirate","Civilian","Pirate","Civilian","Pirate","Pirate","Pirate","Pirate","Pirate","Civilian","Government","Civilian","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Civilian","Pirate","Pirate","Civilian","Civilian","Civilian","Civilian","Civilian","Pirate","Civilian","Civilian","Civilian","Pirate","Civilian","Civilian","Pirate","Civilian","Pirate","Civilian","Civilian","Pirate","Civilian","Civilian","Pirate","Pirate","Pirate","Pirate","Civilian","Pirate","Pirate","Pirate","Civilian","Civilian","Civilian","Pirate","Civilian","Pirate","Civilian","Civilian","Civilian","Civilian","Civilian","Government","Government","Government","Government","Pirate","Pirate","Pirate","Government","Pirate","Civilian","Civilian","Pirate","Pirate","Pirate","Pirate","Civilian","Civilian","Government","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Civilian","Civilian","Civilian","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Pirate","Government","Pirate","Pirate","Civilian","Pirate","Pirate","Government","Government","Pirate","Civilian","Pirate","Civilian","Pirate","Pirate"];
var listsubaffiliation = ["Strawhat","Buggy","Buggy","Baroque Works","Baroque Works","Strawhat","Buggy","Evil Drum Kingdom","Newkama Land","Crocodile","Baroque Works","Marines","Donquixote","Donquixote","Pirate","CP9","CP9","Marines","Marines","Marines","Mihawk","Strawhat","Thriller Bark","Thriller Bark","Celestial Dragon","Kid","Heart","Fire Tank","Beast","Beast","Kuja","Impel Down","Revolutionaries","Revolutionaries","Whitebeard","Whitebeard","Whitebeard","Marines","Golden Lion","Blackbeard","Flying","Kozuki","Donquixote","Donquixote","Donquixote","Donquixote","Marines","Barto Club","Tontatta","Dressrosa","Donquixote","Mogaro","Donquixote","Donquixote","Donquixote","Donquixote","Donquixote","Kurozumi","Marines","Tontatta","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Big Mom","Underworld","Big Mom","Big Mom","Revolutionaries","Revolutionaries","Kozuki","Kozuki","Kozuki","Blackbeard","Kurozumi","Kurozumi","Kozuki","Eldoraggo","Warship Island","Marines","Trump","Ocean's Dream","Panz Fry","Accino Family","Evil Drum Kingdom","Amigo","Neo Marines","Neo Marines","Silver Alliance","Breed","World","World","Gran Tesoro","Silver Alliance","Treasure","Treasure","Gran Tesoro","Gran Tesoro","Ann","Roger","Drum Kingdom","Strawhat","Arabasta","Baroque Works","Baroque Works","Arabasta","Gan Fall","CP0","CP9","CP9","CP0","Kuja","Kuja","Whitebeard","Marines","Big Mom","Kozuki","Caesar","Tontatta","Tontatta","Beast","Big Mom","Underworld","Kozuki","SWORD","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Blackbeard","Kurozumi","Kozuki","Kozuki","Strawhat","Schneider","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Beast","Marines","Crocodile","Whitebeard","God's Army","Blackbeard","Blackbeard","Marines","Marines","Caribou","Caesar","Donquixote","Revolutionaries","Trump Siblings","Gasparde"];
var listposition = ["Captain","Captain","Administrator","Agent","Agent","Archaeologist","Administrator","Royalty","Royalty","First Mate","Agent","Rear Admiral","Dyer","Captain","Captain","Agent","Agent","Captain","Captain","Captain","First Mate","Musician","Captain","Reporter","Slave","Captain","Captain","Captain","Captain","Captain","Captain","Warden","Revolutionary Commander","Division Commander","Captain","Division Commander","Division Commander","Vice Admiral","Captain","Captain","Captain","Scabbard","Trebol","Pica","Pica","Executive","Admiral","Captain","Captain","Royalty","Trebol","Assassin","Pica","Diamante","Diamante","Executive","Executive","Scabbard","Commander","Royalty","Captain","Officer","Officer","Sweet Commander","Officer","Officer","Officer","Sweet Commander","Officer","Sweet Commander","Officer","Officer","Trafficker","Chef","Officer","Revolutionary Commander","Revolutionary Commander","Kunoichi","Royalty","Kunoichi","Titanic Captain","Royalty","Royalty","Scabbard","Captain","Citizen","Mercenary","Captain","Citizen","Crewmate","Bounty Hunter","Royalty","Captain","Officer","Vice Admiral","Captain","Captain","Captain","Shipwright","Security Guard","Crewmate","Captain","First Mate","Proprietor","Concierge","Diva","Crewmate","Royalty","Doctor","Bodyguard","Pet","Agent","Bodyguard","Pet","Agent","Pet","Agent","Agent","Gorgon Sisters","Gorgon Sisters","Division Commander","Fleet Admiral","Combatant","Royalty","Pet","Yellow Kabu","Pink Bee","All Star","Combatant","Journalist","Pet","Captain","Tobiroppo","All Star","All Star","Tobiroppo","Tobiroppo","Tobiroppo","Tobiroppo","Captain","Titanic Captain","Royalty","Pet","Combatant","Captain","Pet","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Marys","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Gifter","Marys","Gifter","Gifter","Vice Admiral","Captain","Division Commander","God","Crewmate","Captain","Admiral","Fleet Admiral","Captain","Scientist","Officer","Chief of Staff","First Mate","Captain"];

const Fruit = {
    fruit: "",
    type: "",
    subtype: "",
    canon: false,
    user: "",
    appearance: "",
    subappearance: "",
    affiliation: "",
    subaffiliation: "",
    position: "",
};

var fruitList = [];

for (let i = 0; i < listfruits.length; ++i) {
    fruitList[i] = Object.create(Fruit);
    fruitList[i].fruit = listfruits[i];
    fruitList[i].type = listtype[i];
    fruitList[i].subtype = listsubtype[i];
    fruitList[i].canon = listcanon[i];
    fruitList[i].user = listusers[i];
    fruitList[i].appearance = listappearance[i];
    fruitList[i].subappearance = listsubappearance[i];
    fruitList[i].affiliation = listaffiliation[i];
    fruitList[i].subaffiliation = listsubaffiliation[i];
    fruitList[i].position = listposition[i];

    if (listsubtype[i] == "SMILE") {
        fruitList[i].user += "(Gifter)";
    }
    if (listaffiliation[i] == "Pirate") {
        fruitList[i].subaffiliation += " Pirates";
    }

}